### ISSUE TITLE
Condition card inside/outside range doesn't work

### ISSUE THREAD

**Issue by dicknystrand** [koktaildotcom/com.koktail.beacon#25] opened 2019-05-20 11:10 UTC
After update to ver 1.2.7 You can't use condition The beacon is inside range for a specific beacon.

![image](https://user-images.githubusercontent.com/37040361/58017456-93b77100-7b00-11e9-8153-f62ca8466c99.png)

**Comment by dicknystrand** [comment] 2019-05-21 11:30
![Anteckning 1](https://user-images.githubusercontent.com/37040361/58092495-8a93d600-7bcc-11e9-9aa8-820b3a1906e3.jpg)
![Anteckning 2](https://user-images.githubusercontent.com/37040361/58092501-8e275d00-7bcc-11e9-8e77-ef81805c2eaa.jpg)
![Anteckning 3](https://user-images.githubusercontent.com/37040361/58092510-91224d80-7bcc-11e9-9fb4-c0b0a6f40259.jpg)

**Comment by koktaildotcom** [comment] 2019-05-21 18:06
I cannot reproduce the issue. Can you re-add your beacons and try again?

On what Homey version are you?

**Comment by dicknystrand** [comment] 2019-05-21 19:45
Hi 

No change, still same behavier. It won´t report out of range, only device unavailible. I have becon installed on my 2 homeys. Same thing on both of them. The problem started after the beacon update.

**Comment by koktaildotcom** [comment] 2019-05-21 19:55
On what homey version are you?
Have you re-paired the beacons?
Can you - step by step - describe what you experiance is and what you would expected?

**Comment by dicknystrand** [comment] 2019-05-22 17:54
Hi 

I'm running on 2.1.2. I have  re paired the Beacons and added a brand new.
I want to use  the  card  "The  Beacon is inside range" in and possission in the flow. But it won't work if the status is "Device is unavailable" It worked intill the upgrade.

⁣Skickat från Blue ​

Den 21 maj 2019 21:55, kI 21:55, koktaildotcom <notifications@github.com> skrev:

**Comment by koktaildotcom** [comment] 2019-05-23 06:15
This issue is resolved in 2.1.8 and is currently in review by athom. Thanks for submitting the issue!

**Closed as completed by koktaildotcom** 2019-05-23 06:15 UTC

**Comment by dicknystrand** [comment] 2019-08-24 09:53
Hi No change, still same behavier. It won?t report out of range, only device unavailible. I have becon installed on my 2 homeys. Same thing on both of them. The problem started after the beacon update.tis 21 maj 2019 kl. 20:06 skrev koktaildotcom <notifications@github.com>:I cannot reproduce the issue. Can you re-add your beacons and try again?

?You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
